### ISSUE TITLE
any reference paper

### ISSUE THREAD

**Issue by jeannotes** [xjlqr/SCAN2CAD#3]
can I get some reference materials for better uderstanding? thanks

**Comment by xjlqr** [comment]
It eventually eventually led to this publication:

A RANSAC Based CAD Mesh Reconstruction Method Using Point Clustering for Mesh Connectivity. 
In International Conference on Machine Vision and Applications (ICMVA) (4 ed.)

I've attached a pdf with a 2D sketch of the method.

[mesh_2d_primer.pdf](https://github.com/xjlqr/SCAN2CAD/files/6632575/mesh_2d_primer.pdf)
